- name: copy nginx config
  copy:
    src: mastodon.nginx
    dest: /etc/nginx/sites-enabled/mastodon
    mode: '0644'
  become: yes
  notify:
    - reload nginx

- name: ufw allows nginx
  ufw:
    rule: allow
    name: Nginx Full
  become: yes
