- name: rbenv setup script
  script:
    cmd: setup-rbenv.sh
    creates: /home/mastodon/.rbenv/plugins/ruby-build
  become_user: mastodon
  become: yes

# ansible evades ~/.bashrc, so we have to manually path to, or load, rbenv

- name: rbenv install
  shell:
    chdir: /home/mastodon/live
    cmd: env RUBY_CONFIGURE_OPTS=--with-jemalloc ~mastodon/.rbenv/bin/rbenv install 2.6.5
    creates: /home/mastodon/.rbenv/versions/2.6.5
  become_user: mastodon
  become: yes

- name: rbenv global
  shell:
    chdir: /home/mastodon/live
    cmd: ~mastodon/.rbenv/bin/rbenv global 2.6.5
  become_user: mastodon
  become: yes

- name: gem update
  shell:
    cmd: 'eval "$(~mastodon/.rbenv/bin/rbenv init -)" && gem update --system'
  become_user: mastodon
  become: yes

- name: bundler install
  shell:
    cmd: 'eval "$(~mastodon/.rbenv/bin/rbenv init -)" && gem install bundler --no-document --force'
  become_user: mastodon
  become: yes
