- name: recovery key
  copy:
    src: id_root.pub
    dest: /root/.ssh/authorized_keys
    owner: root
    group: root
    mode: '0600'
  become: yes

- name: sshd_config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload ssh
  become: yes
